version: '3'

services:
    postgres:
        image: postgres
        restart: always
        environment:
          - POSTGRES_PASSWORD=pass123
        ports:
          - '5432:5432'
   
    pgadmin:
        container_name: pgadmin_4_con
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
          - '5050:80'
